### ISSUE TITLE
Cannot update data in view after put request because data gets reset after successful submission

### ISSUE THREAD

**Issue by raniesantos** [spatie/form-backend-validation#11]
I have a form with a single text field named `content`.
Let's say it's default value is "Taylor".
And then I type into the field and change it's value to "Jeffrey".
After a successful put request, I want to emit the updated value (which is Jeffrey) to the parent to reflect the change in the view.

```js
onUpdateQuote() {

	// At this point in the code, the value of this.form.content is "Jeffrey"
	// since I typed into the form and changed it
	console.log('before ajax request: ' + this.form.content);

	this.form.put(appUrl.api('/quote/update/' + this.qt.id).withToken())
	.then(response => {

		// However, upon success, the value of this.form.content goes back to "Taylor"
		// I wish to send the updated value "Jeffrey" via $emit
		// but I can't because it has been reset
		console.log('after ajax request: ' + this.form.content);

		this.editing = false;
		this.$emit('quoteUpdated', {
			id: this.qt.id,
			content: this.form.content
		});
		// this.$store.commit('setAlert', response.message);
	})
	.catch(error => console.log(error));
}
```

Is this actually the intended behavior?

**EDIT:** I saw this in the code so I guess it was intended. What if you make it so that put requests don't execute a form reset? Are there any cases where it would cause problems?

```js
onSuccess() {
	this.reset();
}
```

**Comment by jackbraj** [comment]
@raniesantos 
You are right I also believe that reset method should not be called automatically, at least for PUT and PATCH requests.

This package is more inclined towards laravel and expects things to be done a certain way on the back end. for example, there is no way to sync defaultData with new data after a PUT or PATCH request so that I can say "hey now my default data is this" (this will also solve the reset problem).

However, I can work around these things myself but I think that would be far from ideal to make a pull request here.

**Comment by sebastiandedeyne** [comment]
We mostly use this for empty forms, in which case a reset is a good thing, but I understand that in the case of an update it's a hindrance.

For now you could overwrite the `onSuccess` method when using it for update forms. Not sure yet where we want to go with this.

**Comment by sebastiandedeyne** [comment]
Changing this would be a breaking change, so we're gonna keep it as is for now.

In the mean time you can overwrite the `onSuccess` method via inheritance or by overwriting the property.

```js
// Inheritance
class EditForm extends Form {
    onSuccess() {}
}

// New property
const myForm = new Form();
myForm.onSuccess = () => {};
```

**Comment by raniesantos** [comment]
Just a follow-up idea, since the Form constructor currently only takes form data as the first and only parameter, maybe it can have a second optional parameter to take in certain options (just like most javascript libraries, except in this case the options are the 2nd parameter) such as setting the reset behavior to false.
```js
data() {
	return {
		form: new Form({
			firstname: '',
			lastname: '',
			location: ''
		}, {
			reset: false
		})
	}
},
```

**Comment by sebastiandedeyne** [comment]
I'll keep this in mind, but not sure yet. Options like that make sense for a drop-in library, but this is more of an OOP low level helper, not a UI thing so it kinda rubs me in the wrong way to use an options object.

It's not a bad idea, just not 100% convinced yet 😄

**Comment by sebastiandedeyne** [comment]
I added an `options` parameter in `1.5.0`.

```js
const form = new Form(fields, { resetOnSuccess: false });
```
