### ISSUE TITLE
Does it have a solution to upload files?

### ISSUE THREAD

**Issue by caiquecastro** [spatie/form-backend-validation#12]
I was wondering about a solution append files to the data.

**Comment by sebastiandedeyne** [comment]
This package only handles validation. To do an actual upload, you'll need to use a package like [Dropzone.js](http://www.dropzonejs.com).

**Comment by caiquecastro** [comment]
I did some changes to my Form.js:
```
    data() {
        return this.hasFiles() ? this.formData() : this.jsonData();
    }

    /**
     * Return all the form data in json format.
     */
    jsonData() {
        const data = {};

        for (const property in this.originalData) {
            data[property] = this[property];
        }

        return data;
    }

    /**
     * Return all the form data in FormData format.
     */
    formData() {
        const data = new FormData();

        for (const property in this.originalData) {
            let value = this[property];

            if (this.isFile(property)) {
                data.append(property, value, value.name);
                continue;
            }

            if (value == null) {
                value = '';
            }

            data.append(property, value);
        }

        return data;
    }

**Comment by schulzefelix** [comment]
@caiquecastro What is your hasFiles() function doing in your example?

**Comment by ankurk91** [comment]
I found a solution -
https://github.com/sahibalejandro/form-object/blob/master/form.js#L62

**Comment by bivinvinod** [comment]
@sebastiandedeyne So my form get submitted twice, if this package just handles validation only ?? 🤔 I still don't get it, how are you getting only validation errors.

**Comment by sebastiandedeyne** [comment]
@bivinvinod This package submits it and provides access to the validation errors. Could you share a code snippet?

**Comment by bivinvinod** [comment]
@sebastiandedeyne sorry, I was just trying to figure out how this package is working. Saw the laracast series, where data is passed via axios. when a data is passed via axios, the data get saved right. So instead you are submitting the form itself via axios. Thanks for your help by the way.
