### ISSUE TITLE
form.errors.get / form.errors.has aren't working?

### ISSUE THREAD

**Issue by jpmurray** [spatie/form-backend-validation#17]
Calling `form.errors.all()` returns

```
{ 
  "message": "The given data failed to pass validation.", 
  "errors": { "field1": [ "The field1 may not be greater than 2 characters." ] }
}
```

But trying to access it via `form.errors.get('field1')` or `form.errors.has('field1')` returns nothing. What am I doing wrong?

**Comment by sebastiandedeyne** [comment]
Are you using Laravel? If so, which version?

**Comment by jpmurray** [comment]
Ah yes, I'm on 5.5@dev. Checking if everything on my end is ready for the imminent release.

I don't think validation message changed, but that _might_ be it?

**Comment by sebastiandedeyne** [comment]
Pre 5.5, Laravel didn't put the errors in an `errors` key. This library expects a response like this:

```
{ "field1": [ "The field1 may not be greater than 2 characters." ] }
```

When 5.5 comes out, we might change this package to match it and bump the major version. In the mean time, you'll need to either override `Form.onFail` or `Errors.record` from this package, or modify your application's exception handler.

**Comment by jpmurray** [comment]
Excellent, I'll keep a branch until a next version with those modification. Might try and send a PR, but I'm not really well versed in testing with javascript, so I might also leave it to the pros!

Thanks!

**Comment by davidhemphill** [comment]
For those coming along with this issue, you can override Form.onFail like this:

```js
const form = new Form({
  // ...
})

form.onFail = function(response) {
  form.errors.record(response.errors)
}
```

**Comment by sebastiandedeyne** [comment]
Reopening this.

Gonna release a v2 of this package around the time of Laravel 5.5 to match the new response format.

**Comment by sebastiandedeyne** [comment]
This is currently on the master branch and will be part of v2.
