### ISSUE TITLE
init with errors

### ISSUE THREAD

**Issue by huglester** [spatie/form-backend-validation#20]
Hello,

this is indeed nice package, already using it in few popup forms.
When submission goes ajax-only.

But now we came with some situations. where we want to 'reload' the page actually.
What do you think, is there a change something like: 
constructor(data, options, errors) { }

could be added to the constructor? 
Is this something you think could be beneficial? 
Also - maybe you have some more ideas on how this can be solved using current package.

If that would be added, we could just json_encode the errors from validation and pass them to form object.

Thank you!

**Comment by sebastiandedeyne** [comment]
Hmmm, this sounds like an edge case to me so I'm not sure if we'd want to add this to the constructor. Right now you could do something like this:

```js
import Form, { Errors } from 'form-backend-validation';

const myForm = new Form();

form.errors = new Errors(myExistingErrors);
```

**Comment by sebastiandedeyne** [comment]
Gonna close this for now. Feel free to reopen if you disagree with my last commend 😄

**Comment by huglester** [comment]
I am still searchng how woud be best to solve this. But currently doing similar as you've posted. 

Hope I won't need to reopen this:) thanks

**Comment by sebastiandedeyne** [comment]
In v2 I'm adding a static `create` and non-static `withErrors` method, so you can do:

```
Form.create(data).withErrors(errors);
```

**Comment by huglester** [comment]
Very good. Waiting. Thanks:) will switch to 2
