### ISSUE TITLE
Empty errors

### ISSUE THREAD

**Issue by nWidart** [spatie/form-backend-validation#30]
Hello,

I'm trying to setup this package with vuejs. However I'm having issues displaying the errors.

My form data is contained inside the `page` field.

``` js
const form = new Form(this.page);
form.post(route('api.page.page.store'));

console.log(form.errors.all());
```

This returns `{}`
![image](https://user-images.githubusercontent.com/882397/30381802-c27297be-989d-11e7-9004-fdd7f38c7ae8.png)

However, in my network tab I do see the errors:
![image](https://user-images.githubusercontent.com/882397/30381821-cee36320-989d-11e7-8f56-c67a7b91089d.png)

When using the "manual" way, I can access the errors like so:

``` js
axios.post(route('api.page.page.store'), this.page)
    .then(response => {
        console.log(response);
    })
    .catch(response => {
        console.log(response.response.data);
    })
```

Am I missing something?

Thanks!

Edit: this is on laravel 5.5 and 2.0.1 of this package.

**Comment by mathieutu** [comment]
@nWidart I'm not an expert but I think so!
The `form.post` return a promise. So you have to `.then` or `.catch` after your post.

When you `console.log`, the request is not finished yet, so there isn't any error, it's normal.
🙂

**Comment by sebastiandedeyne** [comment]
Great call that could be it! `await` could do the trick to if your environment allows it.

```js
const form = new Form(this.page);
await form.post(route('api.page.page.store'));

console.log(form.errors.all());
```

**Comment by nWidart** [comment]
Very js-noob here. 😄 

I've tried @mathieutu 's solution like so:

``` js
form.post(route('api.page.page.store'))
.then(response => {

})
.catch(response => {
    form.errors.all()
});
```

I've also tried await, which errors during building with
```
Syntax Error: await is a reserved word (138:16)
```

**Comment by sebastiandedeyne** [comment]
That's how the package works. Generally you don't need to do that yourself in usage though, but you retrieve the errors in your view template where they belong.

Could you share a bit more context of the component you're working on? Then I could take a look how to best structure it.

**Comment by nWidart** [comment]
Hm I see, but that error object does not contain the helpers like `has`, `get` etc.

**Comment by sebastiandedeyne** [comment]
It does! `form.errors.has('foo')`, `form.errors.first('foo')`, `form.errors.get('foo')` should all work when the `errors` object is populated.

**Comment by sebastiandedeyne** [comment]
Alternatively, the form has methods too. `form.hasError('foo')`, `form.getError('foo')`, `form.getErrors('foo')`

**Comment by mathieutu** [comment]
@sebastiandedeyne it's ok, I'm on the phone with @nWidart and it works 😉 
You can close it.

**Comment by nWidart** [comment]
Indeed, thanks @sebastiandedeyne and @mathieutu for the hands-on help!

[Here is the updated component](https://github.com/AsgardCms/Platform/blob/master/Modules/Page/Assets/js/components/PageForm.vue#L137), in wip, but at least displays some errors. 👍
