### ISSUE TITLE
Form goes to catch on 200 response

### ISSUE THREAD

**Issue by nWidart** [spatie/form-backend-validation#31]
Hello,

Probably yet another stupid question :D

I'm able to validate and display the errors on the form.
However, after fixing the errors (entering the fields), and re-submitting the form, it still goes into the `catch` callback. Yet in the network tab I see a `200 ok` reponse from laravel. And my resource is created correctly in the database.

I'm not sure why it doesn't go into the `then` callback.

``` js
this.form.post(route('api.page.page.store'))
    .then(response => {
        this.loading = false;
        vm.$message({
            type: 'success',
            message: response.data.message
        });
        window.location = route('admin.page.page.index');
    })
    .catch(error => {
        this.loading = false;
        vm.$notify.error({
            title: 'Error',
            message: 'There are some errors in the form.'
        });
    });
```

Is there something else to do?

Thanks

Edit: even when entering the form correctly from the first time, ie it never went into the `catch` callback, it stills goes into it, even though laravel returns a 200.

Edit: [here is the full onSubmit method called.](https://github.com/AsgardCms/Platform/blob/master/Modules/Page/Assets/js/components/PageForm.vue#L146)

**Comment by nWidart** [comment]
If I use the manual way to submit the form, it does go through the `then` callback as expected if there are no errors.

```
axios.post(route('api.page.page.store'), _.merge(this.page, {tags: this.tags}))
    .then(response => {
        this.loading = false;
        vm.$message({
            type: 'success',
            message: response.data.message
        });
        window.location = route('admin.page.page.index');
    })
    .catch(error => {
        this.loading = false;
        vm.$notify.error({
            title: 'Error',
            message: 'There are some errors in the form.'
        });
    })
```

**Comment by sebastiandedeyne** [comment]
Could you post a dump of the `error` variable inside `catch`?

**Comment by nWidart** [comment]
In case of a real error:
```
Error: Request failed with status code 422
    at createError (app.js:12595)
    at settle (app.js:31658)
    at XMLHttpRequest.handleLoad (app.js:12469
```

In case of a successful submit:

```
TypeError: Cannot read property 'message' of undefined
    at app.js:69956
    at <anonymous>
```

**Comment by freekmurze** [comment]
Long shot: what is the output when dumping `error.response`?

**Comment by sebastiandedeyne** [comment]
```diff
  vm.$message({
      type: 'success',
-     message: response.data.message
  });
```

`response.data` doesn't exist here, causing an error. `catch` is called when anything in the `then` chain goes wrong, not just when there's an error in the promise itself.

**Comment by nWidart** [comment]
oh man, thanks! I didn't know that catch also catches errors in `then`. 😄 

I expected `message: response.data.message` because another component (a delete component) does has that structure. Curious here it's just `response.message` instead.

Thanks a lot for the help! 👍
