### ISSUE TITLE
Catching 500 errors

### ISSUE THREAD

**Issue by gizburdt** [spatie/form-backend-validation#39]
Sometimes the application will throw a 500 error. Is there a way to handle/catch/show those with this package?

Thanks :)

**Comment by sebastiandedeyne** [comment]
Gonna need to try it out, but I think you can catch the status in the promise.

```js
form.post('/endpoint').catch(error => console.log(error.response.code));
```

**Comment by gizburdt** [comment]
Yeah, I tries that already, and it works. But was wondering if you have a nice method of storing the error, and showing it. The catch will also catch the validation errors, but I only want the 500 errors in the catch. I know how to fix this issue, but I was wondering if you have a clean(er) way to do it.

**Comment by sebastiandedeyne** [comment]
There currently isn't a better way to do this. I'm not sure if it's possible either since the request methods should return a simple promise. We could add some sort of event system, but I'm not sure I want to maintain that here.

Feel free to discuss / PR is anyone has ideas on this front :)
