### ISSUE TITLE
Suggestion/feature this.form.only(...keys)

### ISSUE THREAD

**Issue by raniesantos** [spatie/form-backend-validation#40]
**Feature description:**

`this.form.only(...keys)`

How would it work?

Similar to how Laravel's `request()->only()` works.

I saw in the source of this package that there's already a `this.form.data()` method.

Basically it's just that but you can pass it an array of fields that it should return.

___

**Example usage:**

I have a use case where I need to `$emit` only the certain fields from large forms to another Vue component.

A method like this would greatly simplify the process.

```js
const fields = {
    foo: this.form.foo,
    bar: this.form.bar
};

// example usage of only()
// const fields = this.form.only(['foo', 'bar']);

this.form.post('/endpoint')
    .then((response) => window.eventBus.$emit('event', fields))
    .catch((error) => console.log(error.response));
```

**Comment by sebastiandedeyne** [comment]
We'd accept a tested PR that adds this method to the `Form` class.

**Comment by raniesantos** [comment]
Hold that thought, I'll go look at how collect.js does `only()`.
