### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by ekrist1** [spatie/form-backend-validation#44]
The new file upload does it only support a single file upload?

This works:
form.file = $event.target.files[0]

This don't work:
this.form.file =  e.target.files || e.dataTransfer.files; 
form.file = $event.target.files

**Comment by sebastiandedeyne** [comment]
@mathieutu Care to jump in? 😄

**Comment by mathieutu** [comment]
Hi ! 
Hem... I totally haven't considered multiple uploads!
I'll dig about that and let you know.

**Comment by ekrist1** [comment]
I haven't read the form-backend code, but I guess you will need to add a loop for appending files. When I'm only using Axios and Loadash, I'm using this method: 

`
methods: {
            uploadFiles(e) { 
            this.formData = new FormData();
             let files = e.target.files || e.dataTransfer.files;
              _.forEach(files, (file) => {
                this.formData.append('items[]', file);
                });
}`

**Comment by mathieutu** [comment]
In fact this part already works, as a FileList is an object, the method is made to convert it to formData.
The problem is from the hasFile method which doesn't search for a FileList object. I'm doing the update and add some tests for that.
