### ISSUE TITLE
[BUG] Request is not handled by php when sending file by PUT method.

### ISSUE THREAD

**Issue by mathieutu** [spatie/form-backend-validation#48]
Hi folks!
Just to let you that I've found a "bug" due to the file upload. 😕

Actually this because of a php bug: if you send data in multipart/form-data, you have to do it by post.
It's an old heritage from times where the requests where made by html form.

see https://github.com/symfony/symfony/issues/9226 for examples and links to explanations.

So if you try to send a form with a file with `form.put` method, php and symfony request will not handle it. I personally managed it by sending it via post and adding the laravel `_method` parameter to be considered as a PUT by Laravel.

I don't know if it's the same in Symfony and didn't try yet.

Maybe we should do something: add the _method automatically/don't convert in formdata if not post /just warn the user/etc

Imo we could warn the user in documentation (maybe with a link the _method tip for the Laravel users) and via a console error if (s)he try to send a file with an other method than post and just send the request without the file.

What are your thoughts about that?

**Comment by mathieutu** [comment]
I can confirm that the `_method`attribute is not handle by Laravel but by Symfony request, so we can use it for a lot of projects, and possibly chose to add it automatically (with a warning for user).

Up to you !

**Comment by sebastiandedeyne** [comment]
Decided we'd rather not maintain this here. We're trying to keep this package agnostic of the backend, and this is a Symfony problem really.

Thanks for bringing this up though, I can imagine this could get in the way at some point, so I documented it in the readme instead :)

**Comment by mathieutu** [comment]
That's perfect! 
(except this is not the fault of the frameworks but php's itself)

**Comment by zKoz210** [comment]
Hmm, I have a strange problem with uploading files.

I have a "block constructor" that dynamically adds new blocks to fill in, including images. But Laravel does not see files until there is at least one file outside of the dynamic array.

![image](https://user-images.githubusercontent.com/28255085/84627229-2f2b3900-aeef-11ea-9772-69e541c2cfa1.png)

"test" is any file you want
"text" consists of the following structure
![image](https://user-images.githubusercontent.com/28255085/84627308-5f72d780-aeef-11ea-8f8b-e8a0e326ca03.png)
"image" is a single file with an image, while there is no "test" field for some reason Laravel writes that no files were loaded

**Comment by mathieutu** [comment]
@zKoz210 Could you please open a new issue for that?
