### ISSUE TITLE
Util.js bug(?)

### ISSUE THREAD

**Issue by ekrist1** [spatie/form-backend-validation#49]
When i add the form-backend package with npm/yarn, the form-backend-validation/dist/util.js file is automatically is created. It seems like the util.js file which is created is a old file without the multiple file upload changes, which causes error with uploading multiple files. 

If i delete the util.js file everything works. I have tried to rebuild the dist manually with npm run build, but the util.js file is not added then. It might be some odd cache issues on my machines, but i have tried on two different Macs and cleared the yarn cache. 

![screen shot 2018-03-01 at 22 11 26](https://user-images.githubusercontent.com/8544305/36870143-625109f2-1d9e-11e8-8066-c591cba60ebd.png)

**Comment by sebastiandedeyne** [comment]
Looks like something was wrong with the build script and this was mis-published in one of the last versions. Tagged a new release that should fix things :)

**Comment by ekrist1** [comment]
hmm, sorry, but it doesn't seems to solve the issue. The util.js file is still dated 29 jan 2018. I'm able to recreate the file with `npx babel dist/util --out-file util.js`. Strange :S

**Comment by sebastiandedeyne** [comment]
Hmm that's odd, if anyone else has this issue please report here!

**Comment by itsgoingd** [comment]
@sebastiandedeyne Hey, I've run into this issue with the latest release which added a new `isFile` helper which is missing in the `dist/utils.js`.

I think the problem is your build script here (https://github.com/spatie/form-backend-validation/blob/master/package.json#L8):

```json
  "build": "rm -rf dist/**/* && babel src -d dist",
```

The rm command will only delete files in dist subdirs in most shells, leaving behind an outdated `dist/util.js`. I'm pretty sure you want to do `rm -rf dist/*` here instead.

**Comment by mathieutu** [comment]
Hey @sebastiandedeyne!
Same here, can't use the package after updating, there is a problem in build process!

**Comment by AdrianMrn** [comment]
@nyeyint I published version 2.3.6 to npm, could you check if this fixes your error? The outdated `util.js` file is now removed before building, so the correct file should now be imported.

Thanks @mathieutu for the PR!

**Comment by nyeyint** [comment]
Hi @AdrianMrn,
Yes already ok for me.

Thanks!
