### ISSUE TITLE
How to upload and validate using this library? 

### ISSUE THREAD

**Issue by muhghazaliakbar** [spatie/form-backend-validation#50]
Anyone can provide to me how to upload and validate file using this library? i dont understand this section https://github.com/spatie/form-backend-validation#working-with-files

**Comment by sebastiandedeyne** [comment]
This library doesn't do anything validation itself, it's a utility library to submit a form to a server, and display errors from the response if necessary.

It works with Laravel's validation out of the box: https://laravel.com/docs/5.6/validation

"Uploading" files is simply uploading files from `input type="file"` elements on form submit.
