### ISSUE TITLE
[Discussion] Detect form changes

### ISSUE THREAD

**Issue by spyric** [spatie/form-backend-validation#53]
I think it will be great feature if we are able to determine forms changes, for example displaying warning about losing data.

Here is my possible realization:
```
hasChanges() {
    const { diff } = require('deep-diff');
    const initial = {};

    for (const property in this.initial) {
        initial[property] = this.initial[property];
    }
    return diff(this.data(), initial) !== undefined;
}
```

But there is two things that I don't like:

1. import library for one signle thing
1. This methods repeat `data` method to get initial properties

For second point I can create method that will accept field name

**Comment by legreco** [comment]
Example: you have a form that you use for updating attributes
before doing form.put it will be useful to check if there is form changes.
