### ISSUE TITLE
how to check for errors with specified keys

### ISSUE THREAD

**Issue by Sabonzy** [spatie/form-backend-validation#54]
i want to be able to pass an array of keys to check if the error bag contains any of them and return true or key/value pair array. maybe something like the `form.only() ` so we will have something like this `form.errors.only()`

**Comment by sebastiandedeyne** [comment]
I'd accept a tested PR that adds support for passing an array to `Errors.any` for this.

https://github.com/spatie/form-backend-validation/blob/1e5b2cc5f94792ee917985ae9e1eba3d1fa25a19/src/Errors.js#L48

E.g.

```js
form.errors.any(['first_name', 'last_name']);
```

**Comment by SamuelNitsche** [comment]
Hey, maybe you can take a look at [my solution](https://github.com/SamuelNitsche/form-backend-validation/tree/support_arrays) and let me know what you think about it.

**Comment by SamuelNitsche** [comment]
I don't really know if I really beat you :) My build has a strange error so I decided to delete my comment and see what the error is :)
