### ISSUE TITLE
required field

### ISSUE THREAD

**Issue by huglester** [spatie/form-backend-validation#55]
Hello,
so for example we have a field Title. which is required...
When first we see the field, we want see it as untouched (no success/error state)

later when we write down the title. - it becomes success
but when we remove whole text from title - we want it become error.

how would you do that?

**Comment by sebastiandedeyne** [comment]
This package doesn't do any validation itself. It's meant to be used with a backend that takes care of that for you, like Laravel (http://laravel.com/docs/5.6/validation)
