### ISSUE TITLE
Support array of objects deep cloning

### ISSUE THREAD

**Issue by dionysiosarvanitis** [spatie/form-backend-validation#56]
Current implementation of `cloneDeep` does not support deep cloning for array of objects since the newly created array contains the references to the original array objects instead of objects itself.

I run into a case while trying to `reset` the form. Form data contained an array of objects (many-to-1 relationship) was binded to a Vue model. After call to `setInitialValues` and array modification, calling `form.reset()` did not revert data back to initial state.

Below is a potential solution to the problem. The array case of `cloneDeep` should be replaced by something like the following:

```js
 if (Array.isArray(object)) {
   const clone = [];

    for (const key in object) {
      if (object.hasOwnProperty(key)) {
        clone[key] = cloneDeep(object[key]);
     }
  }

  return clone;
}
```

Also, copying of File objects should be taken into account for object type cloning. For example

```js
if (object instanceof File || object instanceof FileList) {
    return object;
}
```

**Comment by dionysiosarvanitis** [comment]
`hasFiles` should also look deeper for File existence. Files can leave inside an object and not necessarily in a `FileList`. In my model there is a array like below:
```
reports: [{
  certno: '',
  condition: '',
  comment: '',
  file: File
},{...}]
```

**Comment by mathieutu** [comment]
Hey folks!
I had exactly the same issue, and was making the PR to fix it before seeing that, so thank you @dionysiosarvanitis for it!

@sebastiandedeyne, is it possible to merge https://github.com/spatie/form-backend-validation/pull/63? What's the problem with it?

Thanks!

**Comment by sebastiandedeyne** [comment]
Merged and tagging a new release 👍
