### ISSUE TITLE
Wrong result on errors.has

### ISSUE THREAD

**Issue by larsjanssen6** [spatie/form-backend-validation#60]
Hi,

Awesome package. Is it up to date with Laravel 5.6? Because when I do:

```
form.errors.has('name')
```

I get this:

```
[ "The email to field is required." ]
```

I would expect:

```
The email to field is required.
```

Any idea? Thankyou!

**Comment by sebastiandedeyne** [comment]
This is as expected. You should use the `first` method, just like in Laravel.

```
form.errors.first('name')
```

**Comment by larsjanssen6** [comment]
Thanks!
