### ISSUE TITLE
Handle fetching error message for array validation

### ISSUE THREAD

**Issue by ninjaparade** [spatie/form-backend-validation#62]
The issue in a nutshell is as follows.

if I am sending a request to the server that looks like this. 

```php
 'dates' => [ 
     ['starts_at' =>  '09:00', 'ends_at' => '16:00'],
]
```

I can properly check if the error for `dates` exists 
 ``` javascript 
this.form.has('dates') // true
```
The issue is when I try to get the error message which will be returned form Laravel as `dates.0.starts_at` and `dates.0.ends_at` 

so when I try to fetch that error message 

```javascript 
this.form.errors.first('dates') // ''
this.form.errors.get('dates') // [ ]
```

which is not ideal.

I suggest changing the `first(field)` method to be the following.

```javascript

  first(field) {
    let message = this.get(field)[0]

    if (message === undefined) {
      const errors = Object.keys(this.errors).filter(
        e => e.startsWith(`${field}.`) || e.startsWith(`${field}[`)
      )
      if (errors.length > 0) {
        message = this.first(errors[0])
      }
    }

    return message
  }

```

so that _if_ `this.form.has('dates')` returns true, I can get the error message using `this.form.first('dates)` rather than having to know the index of the error.

What are your thoughts?

Thanks, 

- Ninja

**Comment by ninjaparade** [comment]
@legreco you're assuming you know the index of the error you're going to be getting with that syntax which is exactly what I'm trying to avoid having to do. 👌

**Comment by legreco** [comment]
Are you using a javascript framework?

**Comment by ninjaparade** [comment]
@legreco before I answer that question, please explain to me how or why this has _any_ relevance to what I've suggested above. I am assuming you've read and understood what the issue is? I am 100% confused as to why you're suggesting I use an index and what a JS framework has to do with this.

**Comment by ninjaparade** [comment]
The issue is this.

If I want to show the error for dates, in one spot and get the first one I need to know the index of the error. I can't properly use `this.form.errors.first('dates')`

where I can get a true/false if dates triggered an error by using `.has('dates')` without knowing the index. 

Does this make sense to you?

**Comment by legreco** [comment]
I understand your problem. But in order to suggest you an optimal solution, can you share with me some piece of code?

**Comment by ninjaparade** [comment]
I don't need suggestions :D I am suggesting a change to the Errors.js class so it works properly. @sebastiandedeyne perhaps you can weigh in?
