### ISSUE TITLE
[QUESTION] - How to use PUT/PATCH to submit data

### ISSUE THREAD

**Issue by M-Abdullahi** [spatie/form-backend-validation#69]
Sorry for the dumb question. I am trying to submit a put/patch request but getting 'method not allowed' exception.  

I am using version 1.8.0 & Laravel 5.4
[blade edit view](https://ibb.co/7gHxm7Y)
[vue component](https://ibb.co/wgjL3ws)

I also tried to submit a hidden input field with put/patch as value but failed.

**Comment by lamberttraccard** [comment]
@M-Abdullahi Did you properly register a route in your web.php file ?

**Comment by M-Abdullahi** [comment]
Hi @lamberttraccard. I am using 
``` Route::resource('groups', 'GroupsController'); ``` 
so it should automatically register the route

**Comment by M-Abdullahi** [comment]
After tinkering around, I decided to upgrade to version 2.3.4. 
I used hidden input field that spoofs the method name and all is working now.
