### ISSUE TITLE
"File is not defined" error when used wit nuxtjs ssr

### ISSUE THREAD

**Issue by binaryweavers** [spatie/form-backend-validation#74]
Just installed package @2.3.6 (2.3.7 is not sync with npm yet). With a basic use I am getting this error 
"File is not defined" 
```
import Form from 'form-backend-validation'

data(){
    return {
        form: new Form ({
            email:'',
            password:''
        })
     }
  }
```
![image](https://user-images.githubusercontent.com/19465738/51997950-96eb0a80-24d9-11e9-80b4-3edd640afc4a.png)

**Comment by DJafari** [comment]
workaround before fix this issue :

in your `nuxt.config.js`:
```javascript
global.File= typeof window === 'undefined' ? Object : window.File
global.FileList= typeof window === 'undefined' ? Object : window.FileList
```

**Comment by binaryweavers** [comment]
@DJafari Thanks for your assistance. I have fixed the issue locally modifying the `isFile` function in `util/objects.js` file this way:
```
export function isFile(object) {
    return object && (object.constructor.name == 'File' || object.constructor.name == 'FileList');
}
```
and have put the source in plugins directory

**Comment by DJafari** [comment]
@binaryweavers with my approach you don't need edit dependency file

Anyway, you know what you like

**Comment by binaryweavers** [comment]
> @binaryweavers with my approach you don't need edit dependency file
> 
> Anyway, you know what you like

Yeah I appreciate and would prefer your solution. Just mentioned how I did that. Your solution would take care of other packages too, having such issues
