### ISSUE TITLE
Typo in example of `form.populate()` in readme?

### ISSUE THREAD

**Issue by bakerkretzmar** [spatie/form-backend-validation#75]
Great package, thank you! The readme says that when using `form.populate()` “the populated fields **won’t** override the initial fields.” Is it supposed to say they *will* override the initial fields?

I'm setting initial values and calling `form.populate()`, and it definitely does override them (which is what I would expect, and what I want). As far as I can tell from the `merge()` and `cloneDeep()` helpers, this is the intended behaviour.

**Comment by freekmurze** [comment]
Fixed!
