### ISSUE TITLE
Passing HTTP object to the form

### ISSUE THREAD

**Issue by M-Abdullahi** [spatie/form-backend-validation#76]
Hi. I am currently using 
```
form: form({
  label: "",
  anotherLabel: ""
}, {
    http: httpClient
   }
)
```
approach to pass my custom http client library. 
This doesn't scale up well and leads to repetitive code. Can someone please show me a better way to do this.

**Comment by sebastiandedeyne** [comment]
Sorry, at the moment this is the only way to do this. Feel free to open a PR that makes improvements here.

**Comment by M-Abdullahi** [comment]
Hi.
Sorry for the late reply. 
in case anyone stumbles upon this, I ended up extending the form class and overriding the withOptions method. 

```
import Form from 'form-backend-validation'
import httpClient from './axios'

class ModifiedForm extends Form {
  withOptions (options) {
    options = {
      resetOnSuccess: true,
      http: httpClient
    }
    return super.withOptions(options)
  }
}

export default ModifiedForm
```
