### ISSUE TITLE
How to pass Bearer Token?

### ISSUE THREAD

**Issue by ChristianGiupponi** [spatie/form-backend-validation#87]
Can't find any in docs about how to passa tokens or authorization headers.
Any clue?

**Comment by sebastiandedeyne** [comment]
You'll have to globally set them up on Axios, as this package uses it by default.

See Laravel's `bootstrap.js` as an example: https://github.com/laravel/laravel/blob/d82bf9768b5d486d08159c191bec8a3d7b426436/resources/js/bootstrap.js#L11

If you can't set it up globally, you can pass a custom Axios instance to the form object.

```js
new Form({ /* ... */ }, {
  http: axios.create({ headers: { /* ... */ })
});
```
