### ISSUE TITLE
[BUG] Request is not handled by Laravel when sending file in array

### ISSUE THREAD

**Issue by zKoz210** [spatie/form-backend-validation#92]
Hmm, I have a strange problem with uploading files.

I have a "block constructor" that dynamically adds new blocks to fill in, including images. But Laravel does not see files until there is at least one file outside of the dynamic array.

```
form: new Form({
    test: '',
    name: '',
    text: [],
    _method: 'PUT',
}, {
    resetOnSuccess: false,
}),
```

"test" is any file you want
"text" consists of the following structure
![image](https://user-images.githubusercontent.com/28255085/84627308-5f72d780-aeef-11ea-8f8b-e8a0e326ca03.png)
"image" is a single file with an image, while there is no "test" field for some reason Laravel writes that no files were loaded

Gist example: https://gist.github.com/zKoz210/b5336d804d41e2f21ab0a6a88a0850a2

**Comment by Woloja** [comment]
Yep, i too have this problem. Have any solutions?

**Comment by zKoz210** [comment]
Alternatively, add 'test'with any file, then it will work correctly
