### ISSUE TITLE
Pass arbitrary options to Axios

### ISSUE THREAD

**Issue by dionysiosarvanitis** [spatie/form-backend-validation#94]
Hi! 

I'm in a case where I have to change axios prop `responseType` to `blob`, but I can't find any way to pass arbitrary [options](https://github.com/axios/axios#request-config) to axios. It would be nice if `submit` could handle this like below:

```js
    submit(requestType, url, options) {
        this.__validateRequestType(requestType);
        this.errors.clear();
        this.processing = true;
        this.successful = false;

        return new Promise((resolve, reject) => {
            this.__http[requestType](
                url,
                this.hasFiles() ? objectToFormData(this.data()) : this.data(),
                options
            )
       ...
```

Solution is backward compatible. Of course, restful api methods (post,put, etc.) also have to change.

**Comment by freekmurze** [comment]
I'd accept a PR that adds an easy way to set this.
