### ISSUE TITLE
"Require is not defined" error on Vite production builds

### ISSUE THREAD

**Issue by climberdigital** [spatie/form-backend-validation#97]
There is a Vite compatibility issue [at line 68 of Form.js](https://github.com/spatie/form-backend-validation/blob/a8121d5ea477e669cdf05c49444b4c91ed999621/src/Form.js#L68) as there is a condition that uses require(), which is officially not supported by Vite.

It breaks the rendering of any components that import and use form-backend-validation package in production builds compiled with Vite, throwing a "ReferenceError: require is not defined".

**Comment by DanJamesMills** [comment]
I have the same problem @climberdigital did you mange to find a fix?

**Comment by DanJamesMills** [comment]
I quick way to fix this error is to add 'window.axios = Axios;' to your main.js file that way this code below wont be excuted

```
        const windowAxios = typeof window === 'undefined' ? false : window.axios

        this.__http = options.http || windowAxios || require('axios');
```
